apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-api

  template:
    metadata:
      labels:
        app: devops-api

    spec:
      containers:
        - name: devops-api
          image: swain15/devops-cloud-api:v3

          ports:
            - containerPort: 8000

          env:
            - name: ENVIRONMENT
              value: "production"

            - name: APP_VERSION
              value: "3.0.0"

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20